"""商品新增可上传多张照片

Revision ID: 6a104d3d1765
Revises: 64a867d4fb20
Create Date: 2024-09-29 10:13:31.611828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a104d3d1765'
down_revision = '64a867d4fb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_paths', sa.Text(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_paths')

    # ### end Alembic commands ###
